FROM golang:1.8 AS build
COPY . /go/src/coreos-update-logger

WORKDIR /go/src/coreos-update-logger
RUN go get -d ./... && \
 go get -t && \
 CGO_ENABLED=0 go build -a -ldflags '-s' -installsuffix cgo -o coreos-update-logger .

# copy the binary from the build stage to the final stage
FROM alpine:3.5
RUN apk add --update ca-certificates && \
    rm -rf /var/cache/apk/*
COPY --from=build /go/src/coreos-update-logger/coreos-update-logger /coreos-update-logger
CMD ["/coreos-update-logger"]